# Generated by Django 4.2.24 on 2025-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AlterUniqueTogether(
            name="chatroom",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(fields=("investor", "startup"), name="unique_investor_startup_room"),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
