# Generated by Django 4.2.24 on 2025-10-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="investor_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="startup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="startup_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="chatroom",
            constraint=models.UniqueConstraint(fields=("investor", "startup"), name="unique_investor_startup_room"),
        ),
    ]
