# Generated by Django 4.2.24 on 2025-10-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="investor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="profiles.investorprofile"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notifications.notificationtype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="startup",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="profiles.startupprofile"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["investor", "is_read"], name="notificatio_investo_e480be_idx"),
        ),
    ]
