version: '3.8'

services:
  web:
    build:
      context: ./MiniF
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./MiniF:/app
      - ./MiniF/logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./MiniF/.env
    depends_on:
      - db

  test:
    build:
      context: ./MiniF
      dockerfile: Dockerfile
    volumes:
      - ./MiniF:/app
    working_dir: /app
    environment:
      DJANGO_SETTINGS_MODULE: MiniF.settings
    command: >
      bash -lc "
        coverage run manage.py test &&
        coverage report -m
      "
    depends_on:
      elasticsearch:
        condition: service_healthy
      db:
        condition: service_healthy

  lint:
    build:
      context: ./MiniF
      dockerfile: Dockerfile
    volumes:
      - ./MiniF:/app
    environment:
      - DJANGO_SETTINGS_MODULE=MiniF.settings
      - PYTHONPATH=/app
    working_dir: /app
    command: >
      bash -c "
        BLACK_EXIT=0 &&
        black --check . || BLACK_EXIT=$$? &&
        PYLINT_EXIT=0 &&
        pylint --load-plugins=pylint_django --rcfile=./.pylintrc communications/ core/ dashboard/ MiniF/ profiles/ projects/ users/ || PYLINT_EXIT=$$? &&
        exit $$(($$BLACK_EXIT + $$PYLINT_EXIT))
      "

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=miniF_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=585662vcxz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d miniF_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:latest
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 585662vcxz
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports: ["9200:9200"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - es_data:/usr/share/elasticsearch/data

  celery:
    build: .
    command: celery -A MiniF worker -l info
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - redis
      - web

  krakend:
    build: ./MiniF/krakend
    container_name: krakend
    ports:
      - "8080:8080"
    depends_on:
      - web
      - db
      - redis
      - mongodb
      - elasticsearch
    environment:
      - KRAKEND_PORT=8080
      - KRAKEND_PLUGINS_ENABLED=true
      - KRAKEND_PLUGINS_DIR=/etc/krakend/plugins
    restart: unless-stopped

  smartmatching:
    build:
      context: ./services/Smartmatching
      dockerfile: Dockerfile
    container_name: smartmatching
    env_file:
      - ./services/Smartmatching/.env
    ports:
      - "8003:8003"
    depends_on:
      - db
      - redis
    environment:
      - HF_HOME=/app/cache/huggingface
    volumes:
      - ./services/Smartmatching/app:/app/app
      - ./models_cache:/app/cache
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload


volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  es_data:
