# Generated by Django 4.2.24 on 2025-09-10 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('industry_id', models.IntegerField()),
                ('location', models.CharField(choices=[('Cherkasy', 'Cherkasy'), ('Chernihiv', 'Chernihiv'), ('Chernivtsi', 'Chernivtsi'), ('Dnipro', 'Dnipro'), ('Donetsk', 'Donetsk'), ('Ivano-Frankivsk', 'Ivano-Frankivsk'), ('Kharkiv', 'Kharkiv'), ('Kherson', 'Kherson'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Kirovohrad', 'Kirovohrad'), ('Kyiv', 'Kyiv'), ('Luhansk', 'Luhansk'), ('Lviv', 'Lviv'), ('Mykolaiv', 'Mykolaiv'), ('Odesa', 'Odesa'), ('Poltava', 'Poltava'), ('Rivne', 'Rivne'), ('Sumy', 'Sumy'), ('Ternopil', 'Ternopil'), ('Vinnytsia', 'Vinnytsia'), ('Volyn', 'Volyn'), ('Zakarpattia', 'Zakarpattia'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Zhytomyr', 'Zhytomyr')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
