# Generated by Django 4.2.24 on 2025-10-13 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("industry_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Cherkasy", "Cherkasy"),
                            ("Chernihiv", "Chernihiv"),
                            ("Chernivtsi", "Chernivtsi"),
                            ("Crimea", "Crimea"),
                            ("Dnipro", "Dnipro"),
                            ("Donetsk", "Donetsk"),
                            ("Ivano-Frankivsk", "Ivano-Frankivsk"),
                            ("Kharkiv", "Kharkiv"),
                            ("Kherson", "Kherson"),
                            ("Khmelnytskyi", "Khmelnytskyi"),
                            ("Kirovohrad", "Kirovohrad"),
                            ("Kyiv", "Kyiv"),
                            ("Luhansk", "Luhansk"),
                            ("Lviv", "Lviv"),
                            ("Mykolaiv", "Mykolaiv"),
                            ("Odesa", "Odesa"),
                            ("Poltava", "Poltava"),
                            ("Rivne", "Rivne"),
                            ("Sumy", "Sumy"),
                            ("Ternopil", "Ternopil"),
                            ("Vinnytsia", "Vinnytsia"),
                            ("Volyn", "Volyn"),
                            ("Zakarpattia", "Zakarpattia"),
                            ("Zaporizhzhia", "Zaporizhzhia"),
                            ("Zhytomyr", "Zhytomyr"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="StartupProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Cherkasy", "Cherkasy"),
                            ("Chernihiv", "Chernihiv"),
                            ("Chernivtsi", "Chernivtsi"),
                            ("Crimea", "Crimea"),
                            ("Dnipro", "Dnipro"),
                            ("Donetsk", "Donetsk"),
                            ("Ivano-Frankivsk", "Ivano-Frankivsk"),
                            ("Kharkiv", "Kharkiv"),
                            ("Kherson", "Kherson"),
                            ("Khmelnytskyi", "Khmelnytskyi"),
                            ("Kirovohrad", "Kirovohrad"),
                            ("Kyiv", "Kyiv"),
                            ("Luhansk", "Luhansk"),
                            ("Lviv", "Lviv"),
                            ("Mykolaiv", "Mykolaiv"),
                            ("Odesa", "Odesa"),
                            ("Poltava", "Poltava"),
                            ("Rivne", "Rivne"),
                            ("Sumy", "Sumy"),
                            ("Ternopil", "Ternopil"),
                            ("Vinnytsia", "Vinnytsia"),
                            ("Volyn", "Volyn"),
                            ("Zakarpattia", "Zakarpattia"),
                            ("Zaporizhzhia", "Zaporizhzhia"),
                            ("Zhytomyr", "Zhytomyr"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="startups", to="profiles.industry"
                    ),
                ),
            ],
        ),
    ]
