# Generated by Django 4.2.24 on 2025-09-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='location',
            field=models.CharField(choices=[('Cherkasy', 'Cherkasy'), ('Chernihiv', 'Chernihiv'), ('Chernivtsi', 'Chernivtsi'), ('Crimea', 'Crimea'), ('Dnipro', 'Dnipro'), ('Donetsk', 'Donetsk'), ('Ivano-Frankivsk', 'Ivano-Frankivsk'), ('Kharkiv', 'Kharkiv'), ('Kherson', 'Kherson'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Kirovohrad', 'Kirovohrad'), ('Kyiv', 'Kyiv'), ('Luhansk', 'Luhansk'), ('Lviv', 'Lviv'), ('Mykolaiv', 'Mykolaiv'), ('Odesa', 'Odesa'), ('Poltava', 'Poltava'), ('Rivne', 'Rivne'), ('Sumy', 'Sumy'), ('Ternopil', 'Ternopil'), ('Vinnytsia', 'Vinnytsia'), ('Volyn', 'Volyn'), ('Zakarpattia', 'Zakarpattia'), ('Zaporizhzhia', 'Zaporizhzhia'), ('Zhytomyr', 'Zhytomyr')], max_length=50),
        ),
    ]
