# Generated by Django 4.2.24 on 2025-10-13 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="startupprofile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedproject",
            name="investor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.investorprofile"),
        ),
        migrations.AddField(
            model_name="savedproject",
            name="project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.startupproject"),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="investment_focus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="investors", to="profiles.industry"
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investor_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["industry_id"], name="profiles_st_industr_fd4866_idx"),
        ),
        migrations.AddIndex(
            model_name="startupprofile",
            index=models.Index(fields=["location"], name="profiles_st_locatio_d06a1d_idx"),
        ),
        migrations.AddConstraint(
            model_name="startupprofile",
            constraint=models.UniqueConstraint(fields=("user_id",), name="uniq_startup_per_user"),
        ),
        migrations.AddConstraint(
            model_name="savedproject",
            constraint=models.UniqueConstraint(fields=("investor", "project"), name="unique_investor_project"),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(fields=["investment_focus"], name="profiles_in_investm_314f0d_idx"),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(fields=["location"], name="profiles_in_locatio_d063ad_idx"),
        ),
        migrations.AddConstraint(
            model_name="investorprofile",
            constraint=models.UniqueConstraint(fields=("user_id",), name="uniq_investor_per_user"),
        ),
    ]
