# Generated by Django 4.2.24 on 2025-09-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_startupprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['industry_id'], name='profiles_st_industr_fd4866_idx'),
        ),
        migrations.AddIndex(
            model_name='startupprofile',
            index=models.Index(fields=['location'], name='profiles_st_locatio_d06a1d_idx'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.industry'),
        ),
    ]
