# Generated by Django 4.2.24 on 2025-09-18 08:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("profiles", "0002_alter_startupprofile_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[],
            options={
                "verbose_name": "Investor Profile",
                "verbose_name_plural": "Investor Profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.userprofile",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
