# Generated by Django 4.2.24 on 2025-09-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0003_industry_alter_startupprofile_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Cherkasy", "Cherkasy"),
                            ("Chernihiv", "Chernihiv"),
                            ("Chernivtsi", "Chernivtsi"),
                            ("Crimea", "Crimea"),
                            ("Dnipro", "Dnipro"),
                            ("Donetsk", "Donetsk"),
                            ("Ivano-Frankivsk", "Ivano-Frankivsk"),
                            ("Kharkiv", "Kharkiv"),
                            ("Kherson", "Kherson"),
                            ("Khmelnytskyi", "Khmelnytskyi"),
                            ("Kirovohrad", "Kirovohrad"),
                            ("Kyiv", "Kyiv"),
                            ("Luhansk", "Luhansk"),
                            ("Lviv", "Lviv"),
                            ("Mykolaiv", "Mykolaiv"),
                            ("Odesa", "Odesa"),
                            ("Poltava", "Poltava"),
                            ("Rivne", "Rivne"),
                            ("Sumy", "Sumy"),
                            ("Ternopil", "Ternopil"),
                            ("Vinnytsia", "Vinnytsia"),
                            ("Volyn", "Volyn"),
                            ("Zakarpattia", "Zakarpattia"),
                            ("Zaporizhzhia", "Zaporizhzhia"),
                            ("Zhytomyr", "Zhytomyr"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "investment_focus",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.industry"),
                ),
                (
                    "user_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
