# Generated by Django 4.2.24 on 2025-09-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_investorprofile"),
        ("profiles", "0004_investorprofile"),
    ]

    operations = []
