# Generated by Django 4.2.24 on 2025-09-23 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("profiles", "0004_investorprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "investor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.investorprofile"),
                ),
                (
                    "project",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.startupproject"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="savedproject",
            constraint=models.UniqueConstraint(fields=("investor", "project"), name="unique_investor_project"),
        ),
    ]