# Generated by Django 4.2.24 on 2025-10-02 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0005_savedproject_savedproject_unique_investor_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="investment_focus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="investors", to="profiles.industry"
            ),
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default="2025-09-23 06:24:34.980493"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="investorprofile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investor_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="startupprofile",
            name="industry_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="startups", to="profiles.industry"
            ),
        ),
        migrations.AlterField(
            model_name="startupprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default="2025-09-23 06:20:39.685106"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="startupprofile",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startup_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(fields=["investment_focus"], name="profiles_in_investm_314f0d_idx"),
        ),
        migrations.AddIndex(
            model_name="investorprofile",
            index=models.Index(fields=["location"], name="profiles_in_locatio_d063ad_idx"),
        ),
        migrations.AddConstraint(
            model_name="investorprofile",
            constraint=models.UniqueConstraint(fields=("user_id",), name="uniq_investor_per_user"),
        ),
        migrations.AddConstraint(
            model_name="startupprofile",
            constraint=models.UniqueConstraint(fields=("user_id",), name="uniq_startup_per_user"),
        ),
    ]