# Generated by Django 4.2.24 on 2025-10-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_merge_0003_investorprofile_0004_investorprofile"),
        ("profiles", "0005_savedproject_savedproject_unique_investor_project"),
    ]

    operations = []
