# Generated by Django 4.2.24 on 2025-10-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_merge_0003_investorprofile_0004_investorprofile"),
        ("profiles", "0006_alter_investorprofile_investment_focus_and_more"),
    ]

    operations = []
