# Generated by Django 4.2.24 on 2025-10-13 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StartupProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("likes", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("status", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "startup_profile_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="profiles.startupprofile"),
                ),
            ],
        ),
    ]
