# Generated by Django 4.2.24 on 2025-11-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="startupproject",
            old_name="startup_profile_id",
            new_name="startup_profile",
        ),
    ]
