# Generated by Django 4.2.24 on 2025-09-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
